//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIC_RANKS
    {
        public DIC_RANKS()
        {
            this.PERSON_RANKS = new HashSet<PERSON_RANKS>();
        }
    
        public int DRK_ID { get; set; }
        public string DRK_NAME { get; set; }
    
        public virtual ICollection<PERSON_RANKS> PERSON_RANKS { get; set; }
    }
}
