//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIC_AUDIENCE
    {
        public DIC_AUDIENCE()
        {
            this.PERSON_AUDIENCE = new HashSet<PERSON_AUDIENCE>();
        }
    
        public int DAU_ID { get; set; }
        public string DAU_NAME { get; set; }
    
        public virtual ICollection<PERSON_AUDIENCE> PERSON_AUDIENCE { get; set; }
    }
}
