//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIC_CHAIRS
    {
        public DIC_CHAIRS()
        {
            this.PERSON = new HashSet<PERSON>();
        }
    
        public int DCH_ID { get; set; }
        public string DCH_NAME { get; set; }
    
        public virtual ICollection<PERSON> PERSON { get; set; }
    }
}
