//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGIN
    {
        public string LG_LOGIN { get; set; }
        public string LG_PASSWORD { get; set; }
        public int LG_ISADMIN { get; set; }
        public int LG_PR { get; set; }
    
        public virtual PERSON PERSON { get; set; }
    }
}
