//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace ClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSON
    {
        public PERSON()
        {
            this.PERSON_AUDIENCE = new HashSet<PERSON_AUDIENCE>();
            this.PERSON_CHAIR = new HashSet<PERSON_CHAIR>();
            this.PERSON_RANKS = new HashSet<PERSON_RANKS>();
            this.LOGIN = new HashSet<LOGIN>();
        }
    
        public int PR_ID { get; set; }
        public string PR_NAME { get; set; }
        public int PR_DCH { get; set; }
        public string PR_POS { get; set; }
        public int PR_DDG { get; set; }

        [RegularExpression(@"[0-9]*")]
        public string PR_PH { get; set; }
        public string PR_INT { get; set; }
    
        public virtual DIC_CHAIRS DIC_CHAIRS { get; set; }
        public virtual ICollection<PERSON_AUDIENCE> PERSON_AUDIENCE { get; set; }
        public virtual ICollection<PERSON_CHAIR> PERSON_CHAIR { get; set; }
        public virtual ICollection<PERSON_RANKS> PERSON_RANKS { get; set; }
        public virtual ICollection<LOGIN> LOGIN { get; set; }
        public virtual PERSON PERSON1 { get; set; }
        public virtual PERSON PERSON2 { get; set; }
    }
}
