//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSON_CHAIR
    {
        public int PC_PR { get; set; }
        public int PC_CH { get; set; }
        public int PC_ID { get; set; }
    
        public virtual PERSON PERSON { get; set; }
    }
}
